name: fpmc
version: 1.0
main: com.gmail.fortniteclipperxd.fpmc.P1
commands:
  menu:
    description: Open P1 menu
    usage: /menu
permissions:
    fpmc.*:
        description: Gives access to all fpmc commands
        children:
            fpmc.ticker: true
        fpmc.ticker:
                description: Allows you to use EBlockTickers
                default: op